name: CI

on:
  pull_request:

env:
  HUSKY: 0
  GH_TOKEN: ${{ secrets.GH_SEMANTIC_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_SEMANTIC_TOKEN }} # Custom user with needed permissions
      - name: Setup Git User
        run: |
          git config --global user.name "Rabah Zeineddine"
          git config --global user.email "rabah.zeineddine@hotmail.com"
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx format:check
      - run: npx nx affected -t lint --parallel=3
      - run: npx nx affected -t test --parallel=3 --configuration=ci
      - run: npx nx affected -t build --parallel=3
