name: CI Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, 'chore')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_SEMANTIC_TOKEN }} # Custom user with needed permissions
      - name: Setup Git User
        run: |
          git config --global user.name "Rabah Zeineddine"
          git config --global user.email "rabah.zeineddine@hotmail.com"
      - run: npm ci
      - run: npx nx affected -t build --parallel=3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx nx run-many --targets=build,semantic-release --parallel=false
